name: CI Selenium Test GitHub Actions

on: [push]

permissions:
  id-token: write
  contents: read
  pull-requests: read
  actions: read
  packages: read
  

jobs:
  SeleniumTestRun:

    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v4.1.7
      #- name: Build with Maven
      #  run: mvn clean test
