name: ValueEdgeIntegrationGitHubActions
# Events the integration should be triggered on
on:

  pull_request:
    types: [opened, edited, closed, reopened]
  workflow_run:
    # List of workflows to integrate with ValueEdge
    workflows: [CI Selenium Test GitHub Actions]
    types: [requested, completed]



permissions:
  id-token: write
  contents: read
  pull-requests: read
  actions: read
  packages: read

# Node configuration for allowing HTTPS requests, set to 1
env:
  NODE_TLS_REJECT_UNAUTHORIZED: 1
jobs:
  valueedge_integration_job:
    # List of runner tags
    runs-on: [self-hosted]
    name: ValueEdgeIntegrationGitHubActions#${{github.event.action}}#${{github.event.workflow_run.id}}
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Build with Maven
        run: mvn clean test
      - name: GitHub Actions ValueEdge Integration
        # Reference to our public GitHub action
        uses: MicroFocus/alm-octane-github-actions-integration@v23.3.0
        id: gitHubActionsIntegration
        # Config parameters for the integration
        with:
          # ValueEdge connection data
          octaneUrl: 'https://almoctane-ams.saas.microfocus.com/'
          octaneSharedSpace: 559004
          octaneWorkspace: 2001
          octaneClientId: ${{secrets.ALM_OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.ALM_OCTANE_CLIENT_SECRET}}
          # Automatically provided GitHub token
          githubToken: ${{secrets.GITHUB_TOKEN}}
          # The url that the CI Server in ValueEdge will point to
          serverBaseUrl: https://github.com/Avinash1437KR/Hackathon_Testing
          # Pattern for identifying JUnit style report files for test result injection in ValueEdge
          unitTestResultsGlobPattern: '**/TEST*.xml'